    <div class="container">
        <div class="row">
            <div class="col-md-12">
            <?php View::content() ?>
            </div>
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Por Favor Ingrese lo datos de Usuario</h3>
                    </div>
                    <div class="panel-body">
                        <?php echo Form::open() ?>
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" required placeholder="Username" name="usuario[username]" type="text" autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" required placeholder="ROL (CAPTURISTA)" name="usuario[rol]" type="text" >
                                </div>
                                <div class="form-group">
                                    <input class="form-control" required placeholder="Password" name="usuario[password]" type="password" value="">
                                </div>
                                <div class="form-group">
                                    <input class="form-control" required placeholder="Repetir Password" name="password2" type="password" value="">
                                </div>
                                
                                <!-- Change this to a button or input when using this as a form -->
                                <input type="submit" class="btn btn-lg btn-success btn-block" value="Registrar">
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>