<?php View::content() ?>

	


<div class="panel panel-default">
	  <div class="panel-body results">
		<table class="table">
			<thead>
				<th>#</th>
				<th>Username</th>
				<th>Rol</th>
				<th>Creado</th>
				<th></th>
			</thead>
			<?php foreach ($usuarios as $key => $value): ?>
				<tr>
					<td><?php echo $value->id ?></td>
					<td><?php echo $value->username ?></td>
					<td><?php echo $value->rol ?></td>
					<td><?php echo $value->created ?></td>
					<td>
                        <?php echo Html::link("usuario/delete/$value->id","Eliminar","class='btn btn-danger btn-xs' onclick='if(!confirm(\"Esta Seguro?\")){ return false;}'") ?>               
                    </td>
				</tr>				
			<?php endforeach ?>
			
		</table>
	  </div>
</div>
<?php echo Html::link("usuario/create","Nuevo","class='btn btn-primary'") ?>
<script src="<?php echo PUBLIC_PATH ?>/vendor/jquery/jquery.min.js"></script>
<script src="<?php echo PUBLIC_PATH ?>/vendor/datatables/js/jquery.dataTables.min.js"></script>
<script src="<?php echo PUBLIC_PATH ?>/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
<script type="text/javascript">
	
    $(document).ready(function() {
        $('.table').DataTable({
        	language:{
    "sProcessing":     "Procesando...",
    "sLengthMenu":     "Mostrar _MENU_ registros",
    "sZeroRecords":    "No se encontraron resultados",
    "sEmptyTable":     "Ningún dato disponible en esta tabla",
    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
    "sInfoPostFix":    "",
    "sSearch":         "Buscar:",
    "sUrl":            "",
    "sInfoThousands":  ",",
    "sLoadingRecords": "Cargando...",
    "oPaginate": {
        "sFirst":    "Primero",
        "sLast":     "Último",
        "sNext":     "Siguiente",
        "sPrevious": "Anterior"
    },
    "oAria": {
        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
    }
}
        });
    });
</script>