<?php View::content() ?>
<script type="text/javascript">
	$(document).ready(function(){
		$(".seccion,.pos,.ap,.am,.nombres").keyup(function(){
			var seccion = $('.seccion').val() ? $('.seccion').val() : '';
			var pos = $('.pos').val() ? $('.pos').val() : '';
			var ap = $('.ap').val() ? $('.ap').val() : '';
			var am = $('.am').val() ? $('.am').val() : '';
			var nombres = $('.nombres').val() ? $('.nombres').val() : '';

			$.ajax({
				url:"<?php echo PUBLIC_PATH ?>buscador",
				data:{
					seccion : seccion,
					pos 	: pos,
					ap 		: ap,
					am 		: am,
					nombres : nombres
				},
				type:'post',
				success:function(r){
					console.log(r);
					$(".results").html(r);
				}
			})
		
		});
			$("html").on("keydown",function(e){
				console.log(e.keyCode)
				filas = $(".fila");
				//console.log(filas)
				if (e.keyCode == 65 && e.altKey) {
					//console.log($.trim(filas.eq(0).find("td").eq(1).text()));
					$("#jugador_seccion").val($.trim(filas.eq(0).find("td").eq(4).text()));
					$("#jugador_pos").val($.trim(filas.eq(0).find("td").eq(5).text()));
					$("#jugador_nombres").val($.trim(filas.eq(0).find("td").eq(1).text()));
					$("#jugador_apellido_materno").val($.trim(filas.eq(0).find("td").eq(3).text()));
					$("#jugador_apellido_paterno").val($.trim(filas.eq(0).find("td").eq(2).text()));
				}
				if (e.keyCode == 83 && e.altKey) {
					$("#jugador_seccion").val($.trim(filas.eq(1).find("td").eq(4).text()));
					$("#jugador_pos").val($.trim(filas.eq(1).find("td").eq(5).text()));
					$("#jugador_nombres").val($.trim(filas.eq(1).find("td").eq(1).text()));
					$("#jugador_apellido_materno").val($.trim(filas.eq(1).find("td").eq(3).text()));
					$("#jugador_apellido_paterno").val($.trim(filas.eq(1).find("td").eq(2).text()));
				}

				if (e.keyCode == 68 && e.altKey) {
					$("#jugador_seccion").val($.trim(filas.eq(2).find("td").eq(4).text()));
					$("#jugador_pos").val($.trim(filas.eq(2).find("td").eq(5).text()));
					$("#jugador_nombres").val($.trim(filas.eq(2).find("td").eq(1).text()));
					$("#jugador_apellido_materno").val($.trim(filas.eq(2).find("td").eq(3).text()));
					$("#jugador_apellido_paterno").val($.trim(filas.eq(2).find("td").eq(2).text()));
				}
				if (e.keyCode == 70 && e.altKey) {
					$("#jugador_seccion").val($.trim(filas.eq(3).find("td").eq(4).text()));
					$("#jugador_pos").val($.trim(filas.eq(3).find("td").eq(5).text()));
					$("#jugador_nombres").val($.trim(filas.eq(3).find("td").eq(1).text()));
					$("#jugador_apellido_materno").val($.trim(filas.eq(3).find("td").eq(3).text()));
					$("#jugador_apellido_paterno").val($.trim(filas.eq(3).find("td").eq(2).text()));
				}
				if (e.keyCode == 71 && e.altKey) {
					$("#jugador_seccion").val($.trim(filas.eq(4).find("td").eq(4).text()));
					$("#jugador_pos").val($.trim(filas.eq(4).find("td").eq(5).text()));
					$("#jugador_nombres").val($.trim(filas.eq(4).find("td").eq(1).text()));
					$("#jugador_apellido_materno").val($.trim(filas.eq(4).find("td").eq(3).text()));
					$("#jugador_apellido_paterno").val($.trim(filas.eq(4).find("td").eq(2).text()));
				}
			
			});
			$("html").on("click",".fila",function(e){
				console.log(e.keyCode)
				$(this)
				//console.log(filas)
					//console.log($.trim(filas.eq(0).find("td").eq(1).text()));
					$("#jugador_seccion").val($.trim($(this).find("td").eq(4).text()));
					$("#jugador_pos").val($.trim($(this).find("td").eq(5).text()));
					$("#jugador_nombres").val($.trim($(this).find("td").eq(1).text()));
					$("#jugador_apellido_materno").val($.trim($(this).find("td").eq(3).text()));
					$("#jugador_apellido_paterno").val($.trim($(this).find("td").eq(2).text()));
				
			
			});
	});
</script>
<?php echo Form::open("","post","id='form-jugador'") ?>
	<div class="form-group">
		<label>Datos</label>
		<div class="row">
			<div class="col-md-6">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1"><span class="glyphicon glyphicon-bookmark"></span></span>
					<input type="hidden" name="jugador[equipo_id]" value="<?php echo $equipo_id ?>">
					<?php echo Form::text("jugador.seccion","placeholder='Sección' class='form-control seccion'") ?>
				</div>
			</div>
			<div class="col-md-6">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1"><span class="glyphicon glyphicon-th-large"></span></span>
					<?php echo Form::text("jugador.pos","placeholder='POS' class='form-control pos'") ?>
				</div>
			</div>
		</div>
	</div>
	<div class="form-group">
		<label>Datos Personales</label>
		<div class="row">
			<div class="col-md-4">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1"><span class="fa fa-group "></span></span>
					<?php echo Form::text("jugador.apellido_paterno","placeholder='Apellido Paterno' class='form-control ap'") ?>
				</div>
			</div>
			<div class="col-md-4">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1"><span class="fa fa-group "></span></span>
					<?php echo Form::text("jugador.apellido_materno","placeholder='Apellido Materno' class='form-control am'") ?>
				</div>
			</div>
			<div class="col-md-4">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1"><span class="glyphicon glyphicon-user"></span></span>
					<?php echo Form::text("jugador.nombres","placeholder='Nombres(s)' class='form-control nombres'") ?>
				</div>
			</div>
		</div>
	</div>
	<div class="form-group">
		<label>Domicilio</label>
		<div class="row">
			<div class="col-md-4">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1"><span class="glyphicon glyphicon-road"></span></span>
					<?php echo Form::text("jugador.calle","placeholder='Calle' class='form-control'") ?>
				</div>
			</div>
			<div class="col-md-2">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1">#</span>
					<?php echo Form::text("jugador.numero_int","placeholder='No Interno' class='form-control'") ?>
				</div>
			</div>
			<div class="col-md-2">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1">##</span>
					<?php echo Form::text("jugador.numero_ext","placeholder='No Externo' class='form-control'") ?>
				</div>
			</div>
			<div class="col-md-4">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1"><span class="fa fa-home  "></span></span>
					<?php echo Form::text("jugador.colonia","placeholder='Colonia' class='form-control'") ?>
				</div>
			</div>
		</div>

	</div>
	<div class="form-group">
		<div class="row">
			<div class="col-md-3">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1"><span class="glyphicon glyphicon-envelope"></span></span>
					<?php echo Form::text("jugador.cp","placeholder='C.P' class='form-control'") ?>
				</div>
			</div>
			<div class="col-md-3">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1"><span class="glyphicon glyphicon-globe"></span></span>
					<?php echo Form::text("jugador.localidad","placeholder='Localidad' class='form-control'") ?>
				</div>
			</div>
			<div class="col-md-3">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1"><span class="glyphicon glyphicon-globe"></span></span>
					<?php echo Form::text("jugador.municipio","placeholder='Municipio' class='form-control'") ?>
				</div>
			</div>
			<div class="col-md-3">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1"><span class="glyphicon glyphicon-globe"></span></span>
					<?php echo Form::text("jugador.estado","placeholder='Estado' class='form-control'") ?>
				</div>
			</div>
		</div>
	</div>
	<div class="form-group">
		<label>Datos de Contacto</label>
		<div class="row">
			<div class="col-md-4">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1"><span class="fa fa-phone fa-fw"></span></span>
					<?php echo Form::text("jugador.tlf_particular","placeholder='Teléfono Particular' class='form-control'") ?>
				</div>
			</div>
			<div class="col-md-4">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1"><span class="fa fa-mobile-phone fa-fw"></span></span>
					<?php echo Form::text("jugador.tlf_celular","placeholder='Teléfono Celular' class='form-control'") ?>
				</div>
			</div>
			<div class="col-md-4">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1"><span class="fa fa-envelope-square fa-fw"></span></span>
					<?php echo Form::text("jugador.correo","placeholder='Correo Electrónico' class='form-control'") ?>
				</div>
			</div>
		</div>
	</div>
	<div class="form-group">
		<div class="row">
			<div class="col-md-4">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1"><span class="fa fa-facebook"></span></span>
					<?php echo Form::text("jugador.facebook","placeholder='Facebook' class='form-control'") ?>
				</div>
			</div>
			<div class="col-md-4">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1"><span class="fa fa-twitter"></span></span>
					<?php echo Form::text("jugador.twitter","placeholder='Twitter' class='form-control'") ?>
				</div>
			</div>
			<div class="col-md-4 ">
				<div class="input-group">
					<span class="input-group-addon" id="sizing-addon1"><span class="fa fa-youtube"></span></span>
					<?php echo Form::text("jugador.youtube","placeholder='Youtube' class='form-control'") ?>
				</div>
			</div>
		</div>
	</div>
<div class="pull-right" style="padding-right: 13px">
	
    <div class="row">
        <div class="btn-group btn-breadcrumb">
            <a href="#" class="btn btn-info" id="btn_guardar">Guardar(F5)</a>
            <a href="#" class="btn btn-default" onclick="$('#form-jugador')[0].reset()" id="btn_limpiar">Limpiar(F10)</a>
        </div>
	</div>
</div>
	<script type="text/javascript">
		$(document).ready(function(){
			$("body").on("keyup",function(event){
				//console.log(event.keyCode)
				if (event.keyCode == 121) {
					$('#form-jugador')[0].reset();
				}
			})
			var ctrlKeyDown = false;

			$(document).ready(function(){    
			    $(document).on("keydown", keydown);
			    $(document).on("keyup", keyup);
			});

			function keydown(e) { 

			    if ((e.which || e.keyCode) == 116 || ((e.which || e.keyCode) == 82 && ctrlKeyDown)) {
			        // Pressing F5 or Ctrl+R
			        e.preventDefault();
			        $("#btn_guardar").click();
			    } else if ((e.which || e.keyCode) == 17) {
			        // Pressing  only Ctrl
			        ctrlKeyDown = true;
			    }
			};

			function keyup(e){
			    // Key up Ctrl
			    if ((e.which || e.keyCode) == 17) 
			        ctrlKeyDown = false;
			};
						$("input[type='text']").keyup(function(){
				$(this).val($(this).val().toUpperCase())
			})
			$("#btn_guardar").click(function(e){
				e.preventDefault();
				$("#form-jugador").submit();
			})
			$("#btn_limpiar").click(function(e){
				e.preventDefault();
				$("#form-jugador")[0].reset();
			})
		})
	</script>
<?php echo Form::close() ?>

<div class="clearfix"></div>
<br>
<div class="panel panel-default">
	  <div class="panel-body results">
		
	  </div>

</div>
<br><br><br><br>
<script src="<?php echo PUBLIC_PATH ?>/vendor/jquery/jquery.min.js"></script>
<script src="<?php echo PUBLIC_PATH ?>/vendor/datatables/js/jquery.dataTables.min.js"></script>
<script src="<?php echo PUBLIC_PATH ?>/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
